<?php
require_once __DIR__ . '/../config.php';
require_login();
$pdo = db();
$user_id = $_SESSION['user_id'];
$nickname = $_SESSION['nickname'];
$rooms = $pdo->query('SELECT id,name FROM rooms ORDER BY id')->fetchAll();
?><!doctype html><html><head><meta charset='utf-8'/><title>Chat</title><link rel='stylesheet' href='style.css'></head><body>
  <div class='topbar'><div><button onclick='openSidebar()'>☰ Menu</button> <span style='margin-left:10px;font-weight:bold'>KCA MindConnect</span></div>
  <div>Hi, <b><?php echo e($nickname); ?></b> <button class='dark-toggle' onclick='toggleDarkMode()'>🌙 Dark Mode</button> <a href='logout.php' style='color:#fff;margin-left:8px'>Logout</a></div></div>
  <div id='sidebar'><a href='javascript:void(0)' onclick='closeSidebar()'>✖ Close</a><h3>Dashboard</h3><div style='padding:8px 16px;color:#d8f3dc'><p>Nickname: <b><?php echo e($nickname); ?></b></p><p>Mood today: <span id='mood-today'>😊</span></p><p>Streak: <span id='streak'>🔥 0</span></p><h4>Emergency</h4><p><a href='#' style='color:#95d5b2'>KCA Counsellor</a> · <a href='#' style='color:#95d5b2'>Hotline</a></p><h4>Groups</h4><?php foreach($rooms as $r): ?><div style='padding:6px 0;color:#d8f3dc'><?php echo e($r['name']); ?></div><?php endforeach; ?></div></div>
  <div id='backdrop' onclick='closeSidebar()' style='display:none;position:fixed;inset:0;background:rgba(0,0,0,0.35);z-index:900;'></div>
  <main style='padding:16px;max-width:1100px;margin:0 auto;'><section style='display:grid;grid-template-columns:2fr 1fr;gap:16px'><div><div style='display:flex;justify-content:space-between;align-items:center'><h3>Community Chat</h3><select id='room'><?php foreach($rooms as $r): ?><option value='<?php echo e($r['id']); ?>'><?php echo e($r['name']); ?></option><?php endforeach; ?></select></div><div id='chat' class='chatbox'></div><div style='display:flex;gap:8px;margin-top:8px;max-width:700px'><input id='message' style='flex:1;padding:10px;border-radius:8px;border:1px solid #ddd' placeholder='Type your message...'/><button onclick='sendMsg()'>Send</button></div></div><aside><div class='card'><h4>Mood Check-in</h4><div><button onclick="checkin('😊')">😊</button><button onclick="checkin('😐')">😐</button><button onclick="checkin('😢')">😢</button><button onclick="checkin('😡')">😡</button><input id='moodnote' placeholder='optional note' style='width:100%;margin-top:8px;padding:8px;border-radius:6px;border:1px solid #ddd'/></div><p id='moodstatus' style='color:#4c51bf;margin-top:8px'></p></div></aside></section></main><script src='script.js'></script><script>async function loadMessages(){const roomId=document.getElementById('room').value;const res=await fetch('/api/fetch_messages.php?room_id='+roomId);const data=await res.json();const el=document.getElementById('chat');el.innerHTML='';data.forEach(m=>{const p=document.createElement('p');p.innerHTML='<b>'+m.nickname+':</b> '+m.content;el.appendChild(p);});el.scrollTop=el.scrollHeight;}async function sendMsg(){const content=document.getElementById('message').value.trim();if(!content) return;const roomId=document.getElementById('room').value;await fetch('/api/messages.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({room_id:roomId,content})});document.getElementById('message').value='';await loadMessages();}async function checkin(mood){const note=document.getElementById('moodnote').value;const res=await fetch('/api/mood.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mood,note})});const j=await res.json();document.getElementById('moodstatus').textContent=j.message||'Saved';document.getElementById('mood-today').textContent=mood;document.getElementById('streak').textContent='🔥 '+j.streak;}document.getElementById('room').addEventListener('change',loadMessages);loadMessages();setInterval(loadMessages,3000);</script></body></html>